WGS-TB/MentaLiST

src/mlst_download_functions.jl

Download dbases.xml to $TMPDIR

---

src/mlst_download_functions.jl

Download cgmlst.html file to $TMPDIR

---

src/mlst_download_functions.jl

Save dbases.xml and cgmlst.html to ~/.mentalist

---

src/MentaLiST.jl
src/calling_functions.jl
test/runtests.jl

Relative paths in db

---

conda/meta.yaml
src/mlst_download_functions.jl

Unzip cgMLST schemes using a forked unzip process

---

src/MentaLiST.jl
src/build_db_functions.jl
test/runtests.jl

(partially) addresses #37 for the v0.1 branch.

Store MentaLiST version number in database

---

.travis.yml
test/runtests.jl

Use conda for TravisCI testing environment

---

src/MentaLiST.jl
src/build_db_functions.jl

Fix variable name locus_idx -> idx

---

src/mlst_download_functions.jl

Addresses #54 for MentaLiST-0.1

Use HTTPS to download cgMLST scheme files

---

src/mlst_download_functions.jl

Addresses #54 for MentaLiST-0.2

Use HTTPS for cgmlst.org

---

galaxy/data_managers/data_manager_mentalist_download_enterobase/data_manager/mentalist_download_enterobase.py

Addresses #59 for MentaLiST-0.1

Translate single char into full organism name for galaxy display

---

galaxy/data_managers/data_manager_mentalist_download_enterobase/data_manager/mentalist_download_enterobase.py

Addresses #60 for MentaLiST-0.2

Use full organism name in Tool Data Table for Enterobase downloads

---

galaxy/tools/mentalist_distance/mentalist_distance.xml

Add requirement r-base to mentalist_distance tool

---

src/MentaLiST.jl
src/mlst_download_functions.jl

Addresses #64 for mentalist-0.2 branch.

Update enterobase scheme download URL

---

src/mlst_download_functions.jl

Addresses #64 for MentaLiST-0.1

Update enterobase scheme download URL (v0.1)

---

docs/Basic Usage.ipynb
docs/Novel allele detection with MentaLiST.ipynb
src/calling_functions.jl

alelle->allele

---

src/db_graph.jl

Completely untested, but I wonder if this might be a fix for #91

wrap kmer_coverage_ilp in Base.invokelatest

---

galaxy/data_managers/data_manager_mentalist_download_pubmlst/data_manager/mentalist_download_pubmlst.py

Same as #96 but for mentalist_v0.1 branch.

Replace __pd__ from Galaxy

---

galaxy/data_managers/data_manager_mentalist_download_cgmlst/data_manager/mentalist_download_cgmlst.xml

Add two more cgMLST scheme options to galaxy tool.

---

README.md

Details about WACP was missing. I added them

Add WACP details

---

README.md

MentaLiST 2.0 managed to fix two major bugs about novel alleles

Debugging information about version 2.0
